version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile1 
    ports:
      - "8000:8000"
    depends_on:
      - db

  app2:
    build:
      context: .
      dockerfile: Dockerfile2  

    ports:
      - "8001:8000"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mybd
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

